### ISSUE TITLE
I'm curious about you db design? Where can I find 'create table' sqls in the project ?

### ISSUE THREAD

**Issue by robbine** [VertaAI/modeldb#1193]
At first I thought the 'hibernate-base-db-schema.sql' provides all sql commands, however this file turned out to be an exported sql.
Could you please show me a start point when system is booting and initializing all db tables ?
Many thanks !

**Comment by ravishetye** [comment]
@robbine : ModelDB uses liquibase for database changeset management. 
As for a start point during system booting: that happens at this [code pointer](https://github.com/VertaAI/modeldb/blob/master/backend/src/main/java/ai/verta/modeldb/utils/ModelDBHibernateUtil.java#L453. )

Liquibase starts running tags starting from [chaneglog-1.0.xml](https://github.com/VertaAI/modeldb/blob/master/backend/src/main/resources/liquibase/db-changelog-1.0.xml).

If you are only interested in create tables you can search for `createTable` in the folder `liquibase` to get the relevant sections.

I have tried to annotate the schema diagram generated off current t master branch, hope that helps.
![MDB DB Schema](https://user-images.githubusercontent.com/5742196/89067111-7ea0b980-d323-11ea-8986-a7f01ff4c481.png)

If you have more follow ups , do respond her or reach out to our [slack community ](http://bit.ly/modeldb-mlops)

**Comment by robbine** [comment]
Oh, I see there is a whole lot  of work to make this magic happen.
Thank you for your elaboration !
