### ISSUE TITLE
modeldb-backend not starting 

### ISSUE THREAD

**Issue by adhikari23** [VertaAI/modeldb#1559]
docker-compose -f docker-compose-all.yaml up

here modeldb-backend is failing to create. 
![image](https://user-images.githubusercontent.com/30843806/94639871-d98e6700-02fa-11eb-88a4-4bd51c160ec1.png)

**Comment by anandjakhaniya** [comment]
Hi @adhikari23 ,
From the attached logs, it looks like the modeldb-backend is unable to find the config file `/config/config.yaml` from the environment variable `VERTA_MODELDB_CONFIG`
```
version: "3.5"
services:
  modeldb-backend:
  ...
	environment:
	  - VERTA_MODELDB_CONFIG:/config/config.yaml
	volumes:
	  - ./backend/config:/config/
	  - ./artifact-store:/artifact-store/
  ...
```
that means your system volume `./backend/config` is not properly shared with the docker so can you check the shared volume `./backend/config` is correctly mapped with the docker or not and the docker can use it from the volumes field of the modeldb-backend service in docker-compose-all.yaml?
```
volumes:
  - ./backend/config:/config/
```

Could you share your docker-compose-all.yaml and more details about your setup here? then it would be helpful.

**Comment by adhikari23** [comment]
Hii @ad-47 

This is the docker-compose-all.yaml file which I am using.

version: "3.5"
services:
    modeldb-backend:
        image: vertaaiofficial/modeldb-backend:2.0.8.1
        container_name: "modeldb-backend"
        expose:
            - "8085"
            - "8086"
        ports:
            - "8085:8085"
            - "8086:8086"
        networks:
            - modeldb_network
        environment:
            - VERTA_MODELDB_CONFIG:/config/config.yaml
        volumes:
            - ./backend/config:/config/
            - ./artifact-store:/artifact-store/

    modeldb-proxy:
        image: vertaaiofficial/modeldb-proxy:2.0.8.1
        container_name: "modeldb-proxy"
        environment:
            MDB_ADDRESS: "modeldb-backend:8085"
            SERVER_HTTP_PORT: "8080"
        expose:
            - "8080"
        ports:
            - "8080:8080"
        depends_on:
            - modeldb-backend
        networks:
            - modeldb_network

    modeldb-graphql:
        image: vertaaiofficial/modeldb-graphql:2.0.8.1
        container_name: "modeldb-graphql"
        environment:
            MDB_ADDRESS: "modeldb-backend:8085"
            SERVER_HTTP_PORT: "4000"
            QUERY_PATH: "/api/v1/graphql/query"
        expose:
            - "4000"
        ports:
            - "4000:4000"
        depends_on:
            - modeldb-backend
        networks:
            - modeldb_network

    modeldb-frontend:
        image: vertaaiofficial/modeldb-frontend:2.0.8.1
        container_name: "modeldb-frontend"
        expose:
            - "3000"
        ports:
            - "3000:3000"
        depends_on:
            - modeldb-proxy
            - modeldb-graphql
        environment:
            DEPLOYED: "yes"
            BACKEND_API_PROTOCOL: "http"
            BACKEND_API_DOMAIN: "modeldb-webapp:3000"
            MDB_ADDRESS: http://modeldb-proxy:8080
            ARTIFACTORY_ADDRESS: http://modeldb-backend:8086
            GQL_ADDRESS: http://modeldb-graphql:4000
        networks:
            - modeldb_network

    modeldb-postgres:
        image: postgres
        container_name: "modeldb-postgres"
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - modeldb_network
        volumes:
            - ./data:/var/lib/postgresql/data/pgdata

networks:
  modeldb_network:

**Comment by adhikari23** [comment]
Hii @ad-47 

This is the docker-compose-all.yaml which I am using.


 version: "3.5"
 services:
    modeldb-backend:
        image: vertaaiofficial/modeldb-backend:2.0.8.1
        container_name: "modeldb-backend"
        expose:
            - "8085"
            - "8086"
        ports:
            - "8085:8085"
            - "8086:8086"
        networks:
            - modeldb_network
        environment:
            - VERTA_MODELDB_CONFIG:/config/config.yaml
        volumes:
            - ./backend/config:/config/
            - ./artifact-store:/artifact-store/

    modeldb-proxy:
        image: vertaaiofficial/modeldb-proxy:2.0.8.1
        container_name: "modeldb-proxy"
        environment:
            MDB_ADDRESS: "modeldb-backend:8085"
            SERVER_HTTP_PORT: "8080"
        expose:
            - "8080"
        ports:
            - "8080:8080"
        depends_on:
            - modeldb-backend
        networks:
            - modeldb_network

    modeldb-graphql:
        image: vertaaiofficial/modeldb-graphql:2.0.8.1
        container_name: "modeldb-graphql"
        environment:
            MDB_ADDRESS: "modeldb-backend:8085"
            SERVER_HTTP_PORT: "4000"
            QUERY_PATH: "/api/v1/graphql/query"
        expose:
            - "4000"
        ports:
            - "4000:4000"
        depends_on:
            - modeldb-backend
        networks:
            - modeldb_network

    modeldb-frontend:
        image: vertaaiofficial/modeldb-frontend:2.0.8.1
        container_name: "modeldb-frontend"
        expose:
            - "3000"
        ports:
            - "3000:3000"
        depends_on:
            - modeldb-proxy
            - modeldb-graphql
        environment:
            DEPLOYED: "yes"
            BACKEND_API_PROTOCOL: "http"
            BACKEND_API_DOMAIN: "modeldb-webapp:3000"
            MDB_ADDRESS: http://modeldb-proxy:8080
            ARTIFACTORY_ADDRESS: http://modeldb-backend:8086
            GQL_ADDRESS: http://modeldb-graphql:4000
        networks:
            - modeldb_network

    modeldb-postgres:
        image: postgres
        container_name: "modeldb-postgres"
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - modeldb_network
        volumes:
            - ./data:/var/lib/postgresql/data/pgdata

 networks:
   modeldb_network:

**Comment by anandjakhaniya** [comment]
have you verified the following comment? 

> that means your system volume `./backend/config` is not properly shared with the docker so can you check the shared volume `./backend/config` is correctly mapped with the docker or not and the docker can use it from the volumes field of the modeldb-backend service in docker-compose-all.yaml?
```
volumes:
  - ./backend/config:/config/
```

**Comment by adhikari23** [comment]
I cloned your repo 
And I also did the changes you asked me to do. It is showing the same error.

![image](https://user-images.githubusercontent.com/30843806/94660633-8aa8f780-0323-11eb-8695-467dc075e261.png)

**Comment by anandjakhaniya** [comment]
I am sorry for misleading you for `./backend/config` to `./backend` but please go with https://github.com/VertaAI/modeldb/blob/master/docker-compose-all.yaml file without any changes.

Could you verify your clone repo root folder is properly shared with docker or not? and docker can access `./backend/config`?

**Comment by adhikari23** [comment]
I was using WSL for this whose root folder is not shared with docker.
So, I tried the same thing in Windows cmd.
Now, the backend looks fine, but the postgress is not up.
![image](https://user-images.githubusercontent.com/30843806/94691174-9958d400-034e-11eb-8b93-b0fec89be8c3.png)

**Comment by adhikari23** [comment]
There was issue in the path of postgress volume. Resolved !

**Comment by o0TT0o** [comment]
The docker-compose config file 's :    https://github.com/VertaAI/modeldb/blob/master/backend/config/config.yaml
