### ISSUE TITLE
[Feature] Add more flexible constructors for ModelDBSyncer

### ISSUE THREAD

**Issue by mpvartak** [VertaAI/modeldb#185]
Currently ModelDB syncer can be instantiated from the config or explicitly. Allow the user to override the options read in from config and to provide more flexible explicit constructor.

**Comment by mpvartak** [comment]
@RogerTangos

**Comment by mpvartak** [comment]
- [x] Unify configs for python and scala

- [x] Override config params

**Comment by RogerTangos** [comment]
Resolved in #234
