### ISSUE TITLE
Server installation - did not succeed on my Ubuntu 16.04

### ISSUE THREAD

**Issue by flikka** [VertaAI/modeldb#194]
Missing a commons-lang dependency, and the path to thrift was not the same as on my system. Patch suggestion in https://github.com/mitdbg/modeldb/pull/195

**Comment by mpvartak** [comment]
Does the updated pom resolve the issue?

**Comment by flikka** [comment]
Yes! Installed on Ubuntu 16.04 and RedHat 7.
lør. 18. feb. 2017 kl. 17.33 skrev mpvartak <notifications@github.com>:

**Comment by mpvartak** [comment]
Awesome, great to hear! Will close the issue in that case. Please feel free to reopen/make another issue if you run into any other problems!
