### ISSUE TITLE
[Bug] [Minor] Extraneous error in frontend

### ISSUE THREAD

**Issue by mcslao** [VertaAI/modeldb#199]
@weienlee could you please remove the extraneous error being logged [here](https://github.com/mitdbg/modeldb/blob/c10e592840792e79be22ef4fdc10c765a848b822/frontend/util/api.js#L157)?

**Comment by mpvartak** [comment]
@weienlee ping

**Comment by weienlee** [comment]
fixed in this [commit](https://github.com/mitdbg/modeldb/commit/1da3f69c388130b6315878146cbd52e4e0130adb)
