### ISSUE TITLE
[Bug][Minor] Sizing error 

### ISSUE THREAD

**Issue by cheahuychou** [VertaAI/modeldb#210]
The graph might need to be resized so the axis labels could fit.

<img width="726" alt="screen shot 2017-02-28 at 6 54 48 pm" src="https://cloud.githubusercontent.com/assets/13965431/23441447/4ce1d9bc-fdf0-11e6-9387-dd5fe61d61eb.png">

**Comment by weienlee** [comment]
This [commit](https://github.com/mitdbg/modeldb/commit/e413d5f4797aff366019cf566983265e86dc94d6) should have fixed the issue
