### ISSUE TITLE
[FEATURE] Support python 3.x

### ISSUE THREAD

**Issue by eyadsibai** [VertaAI/modeldb#252]
Being able to install and use the python client with python 3.x

**Comment by RogerTangos** [comment]
Hey @eyadsibai - I'm taking a look at this.

**Comment by eyadsibai** [comment]
Thanks a lot

**Comment by RogerTangos** [comment]
Hey @eyadsibai - could you checkout RogerTangos/python3 and see if it works for you? It's working locally on my machine, but failing the CI tests.

**Comment by eyadsibai** [comment]
Sure I will get back to you in 15 hours. @RogerTangos

**Comment by eyadsibai** [comment]
regarding the CI tests failing. 
the thrift package doesn't support python 3.x it seems 
may be you should switch to this one instead https://github.com/eleme/thriftpy

**Comment by eyadsibai** [comment]
Is there a reason why you have chosen mongodb instead of something simpler like sqlite?

**Comment by RogerTangos** [comment]
Oh, I see. Thrift 0.10.0 is supports python 3, but not thrift 0.9.3. I'll have to update the documentation.
https://pypi.python.org/pypi/thrift/0.10.0
https://pypi.python.org/pypi/thrift/0.9.3

**Comment by RogerTangos** [comment]
There's some discussion of dropping one or the other database. At the moment, we're planning on migrating as much as possible _out_ of sqlite and _into_ mongodb. If it's a big concern though, it'd be worth chiming in on #221

**Comment by eyadsibai** [comment]
Hi @RogerTangos ... Is there an update for python 3 support?

**Comment by mpvartak** [comment]
hey @eyadsibai, the RogerTangos/Python3 works with Python3. We haven't merged it in b/c of intermittent Travis failures that we're looking into. You can give it a spin though!

**Comment by idanh** [comment]
Hey, any updates on when Python3 branch will be merged? Thanks!

**Comment by mpvartak** [comment]
@justinanderson

**Comment by justinanderson** [comment]
@idanh I expect to have the Python 3 branch merged in the next few days. It's marked as MRG, but it still needs some work.

**Comment by idanh** [comment]
@justinanderson sounds great, looking forward to it. Thanks!

**Comment by arsenyinfo** [comment]
Hi guys, are there new estimations when the py3 branch will be merged? Can I help with something? I'd really love to use the tool, but py2 is kind of medieval lang ;(

**Comment by idanh** [comment]
@justinanderson I'd also be happy to help out if thats what it takes to get it merged soon.

**Comment by justinanderson** [comment]
I'm not 100%, but I think I've resolved all of the remaining Python 2/3 issues in the PR.

If anyone wants to test this without checking out the code, I've uploaded a test distribution to PyPi. You can install it with:
```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple modeldb
```

**Comment by idanh** [comment]
@justinanderson , I'll give it a go and update here. Thank you!

**Comment by arsenyinfo** [comment]
@justinanderson i tried a little - works perfectly for me. Would you please upload the package to the main PyPI?

**Comment by mpvartak** [comment]
This branch is merged in. @justinanderson would you mind updating the mdb version on pip? thanks!

**Comment by justinanderson** [comment]
@mpvartak That should be all set now.
