### ISSUE TITLE
please support pyyaml>5.4

### ISSUE THREAD

**Issue by zhuangkechen** [VertaAI/modeldb#2536]
Current verta client need pyyaml>=5.1, <5.4, however many environment are using pyyaml >=5.4.1 now. So when can verta support pyyaml>5.4? Thanks.

**Comment by convoliution** [comment]
Hi @zhuangkechen, thank you for the heads-up!

We'll test and verify our compatibility with the newer `pyyaml` versions to see if we can increase the upper bound.

**Comment by liuverta** [comment]
This should be addressed in the just-released `verta==0.20.0`.

https://github.com/VertaAI/modeldb/issues/2929#issuecomment-1093243827
