### ISSUE TITLE
log_image support?

### ISSUE THREAD

**Issue by elgalu** [VertaAI/modeldb#2585]
Similar to https://www.tensorflow.org/api_docs/python/tf/summary/image or https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.log_image

**Comment by convoliution** [comment]
Hi @elgalu, thank you for the continued interest in ModelDB!

`ExperimentRun` has a `log_image()` method, which you can find documentation for [here](https://verta.readthedocs.io/en/master/_autogen/verta.tracking.entities.ExperimentRun.html?highlight=log_image#verta.tracking.entities.ExperimentRun.log_image).

It mainly supports PIL images:
```python
import PIL
img = PIL.Image.new('RGB', (64, 64), 'gray')
pass  # draw image
run.log_image(key, img)
```

as well as matplotlib plots and figures:
```python
import matplotlib.pyplot as plt
plt.scatter(*np.random.random((2, 10)))
run.log_image(key, plt)
```

**Comment by elgalu** [comment]
Thanks!
