### ISSUE TITLE
Running docker-compose on ubuntu gives error

### ISSUE THREAD

**Issue by vidit-bhatia** [VertaAI/modeldb#264]
I am using an Ubuntu VM on Azure to setup modelDB . I am  using Docker to spin up the instance. When I try to run docker-compose up I get the following error

`
The following packages have unmet dependencies:
 mongodb-org-shell : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'backend' failed to build: The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 &&     echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list &&     apt-get update &&     apt-get install -y         maven         sqlite         g++         make         automake         bison         flex         pkg-config         libevent-dev         libssl-dev         libtool         mongodb-org-shell &&     apt-get clean &&     update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java' returned a non-zero code: 100`

Can someone provide me some pointer what I am doing wrong.

This bug is important as we at Adobe are trying to analyze the feature set of Model DB to see if we can use it for our use case

**Comment by vidit-bhatia** [comment]
I can not add a label to the issue as mentioned in contribution guide because I do not have authorization to do so. Sorry about that

**Comment by vidit-bhatia** [comment]
I found the solution to this problem on ubuntu machines you need to add these two lines in /dockerbuild/Dockerfile-backend

`wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb && \
dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb && \
`

**Comment by justinanderson** [comment]
Hi @vidit-bhatia, thanks for reporting this issue. It'll be fixed by #261.

**Comment by justinanderson** [comment]
#261 has been merged into master, so this issue should be resolved.
