### ISSUE TITLE
[FEATURE] Create a nice Logo/Icon for ModelDB

### ISSUE THREAD

**Issue by FlorianWilhelm** [VertaAI/modeldb#289]
In order to further spread the word about ModelDB it would be really helpful if it had a logo. Right now I cannot really put something visual on a slide if I want to mention ModelDB in a talk. A picture says more than 1000 words ;-)

**Comment by mpvartak** [comment]
Good point! We need to put it up in a more prominent place.

Here it is: https://github.com/mitdbg/modeldb/blob/gh-pages/images/mdb_logo.png

**Comment by FlorianWilhelm** [comment]
Thanks @mpvartak! Although, I am not completely convinced that this qualifies as a *nice* logo ;-) 
Maybe someone from the MIT arts faculty has an idea :-)
