### ISSUE TITLE
Current verta==0.20.0 version doesn't support click>=8.0

### ISSUE THREAD

**Issue by vineeth-shyam** [VertaAI/modeldb#3002]
Hi @liuverta 

In a project we are using verta(0.17.2) library for accessing modeldb and seldon-core(1.2.3) for deploying ML models on Kubernetes. Now due the vulnerabilities in PyYAML < 5.4 we planned to upgrade it. Thank you for the newer version of verta which supports PyYAML==5.4  (#2929). However when upgraded to newer version, seldon-core has a dependency conflict which only supports click >=8.0 whereas verta==0.20.0 doesn't. 

Can you please release a verta version which can support click>=8.0.

[requirements.txt](https://github.com/VertaAI/modeldb/files/8512078/requirements.txt) attached FYR.

Thanks in advance.

**Comment by vineeth-shyam** [comment]
Hi @liuverta 

Any updates?

**Comment by liuverta** [comment]
@vineeth-shyam I've just published `verta==0.20.2` which supports `click>=8.0,<9.0`.

Please let me know if this resolves your use case (and feel free to reopen this issue if it doesn't). Thank you, sincerely, for using our software and thank you for your patience!
