### ISSUE TITLE
docker compose run modeldb not found model registry

### ISSUE THREAD

**Issue by QipengZhou** [VertaAI/modeldb#3072]
Hi, I'm run model by [up and running in 5 minutes](https://github.com/VertaAI/modeldb#up-and-running-in-5-minutes). And all services are running, but I'm not found model registry in http://localhost:3000. What I did wrong?

**Comment by jkwatson-verta** [comment]
Do you have any errors in your docker logs? 

I just verified that this works for me on my laptop, so it might be something specific to your environment.

**Comment by QipengZhou** [comment]
No, I'm not found some errors in my docker logs.
As the follow pic, I can't found model registry in the left menu like in docs [vulnerability-scanning](https://docs.verta.ai/verta/registry/guides/vulnerability-scanning).
![inSPP3ZVmX](https://user-images.githubusercontent.com/5410298/183549396-28a9a758-7555-4458-becf-82049cfcc19a.jpg)

**Comment by QipengZhou** [comment]
Reduplicate with https://github.com/VertaAI/modeldb/issues/2656
