### ISSUE TITLE
HTTPError: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by dagongji10** [VertaAI/modeldb#531]
I have install docker-compose and start the server use `docker-compose -f docker-compose-all.yaml up`, and it run normally, I can find the ModelDB Web UI use `http://localhost:3000`.
![image](https://user-images.githubusercontent.com/15357846/79539982-f2db8800-80b9-11ea-9617-c5af09a59a81.png)
But when I run a model like :
```
from verta import Client
client = Client("http://localhost:3000")

proj = client.set_project("My first ModelDB project")
expt = client.set_experiment("Default Experiment")

# log the first run
run = client.set_experiment_run("First Run")
run.log_hyperparameters({"regularization" : 0.5})
# ... model training code goes here
run.log_metric('accuracy', 0.72)

# log the second run
run = client.set_experiment_run("Second Run")
run.log_hyperparameters({"regularization" : 0.8})
# ... model training code goes here
run.log_metric('accuracy', 0.83)
```
it will get http-error:
![image](https://user-images.githubusercontent.com/15357846/79540390-acd2f400-80ba-11ea-8d3f-deedcb62cb23.png)

how can I solve this?

**Comment by ravishetye** [comment]
Hey @dagongji10 ,
I can not seem to reproduce the issue.
Few questions which will help me debug the issue
1. Does it happen for a brief time or do you always get this issue?
1. Does the docker logs have a line `Backend server started listening on 8085`?
1. Are there any errors in the docker-compose logs? IF you can share the docker-compose  log as well that will provide us more information

**Comment by convoliution** [comment]
Hi @dagongji10,

Could you also let us know what version of the Python client you are using?
It is recommended to use the latest version (`0.14.2`), which can be installed via `pip` or `conda`.

**Comment by dagongji10** [comment]
@ravishetye 

1. It's my first time using model-db, and I got this issue every-time when I try to run the test python script. I guess there is some problem in the way I use model-db, but I did not know where goes wrong.
2. The docker-compose print logs like this:
![image](https://user-images.githubusercontent.com/15357846/79709756-9c5a8d80-82f5-11ea-92d2-f13a8f5d2ac5.png)

**Comment by dagongji10** [comment]
@ravishetye  @convoliution 
Thanks!
I have update my verta version from 0.13.18 to 0.14.2. And the problem is gone.
![image](https://user-images.githubusercontent.com/15357846/79710679-52bf7200-82f8-11ea-9ade-5eea1d0e1b23.png)
Thanks for your help!

**Comment by convoliution** [comment]
Awesome, glad to hear it!
@dagongji10 Keep letting us know if you have any questions or suggestions as you're using ModelDB.
