### ISSUE TITLE
modeldb-graphql image missing

### ISSUE THREAD

**Issue by erichulburd** [VertaAI/modeldb#564]
`docker-compose.all.yml` includes a `modeldb-graphql` service, but that image doesn't seem to exist for [vertaaiofficial](https://hub.docker.com/search?q=vertaaiofficial&type=image) - also is not referenced in `push_to_hub.sh`.

Should it be pulled from docker-compose.all.yml or does that image need to be pushed?

**Comment by conradoverta** [comment]
@erichulburd you are correct, this was an oversight on our end. We're switching some queries to graphql but it's not required yet. We're fixing this ASAP. Thanks for flagging this!

**Comment by erichulburd** [comment]
Also, since we're here, on the dashboard, the link to the docs appears broken: https://verta.readme.io/docs

**Comment by conradoverta** [comment]
@erichulburd got it. I'll send a fix for that too! In the meantime, our docs have moved to https://docs.verta.ai/en/master/ for more flexibility.

**Comment by conradoverta** [comment]
Fixed and waiting review. We'll issue a new build once this is in. Let me know if you find something else!

**Comment by conradoverta** [comment]
The changes have been merged and validated. Closing this, but let us know if you encounter any new issues.
