### ISSUE TITLE
the behavior of run.log_model()

### ISSUE THREAD

**Issue by loveunk** [VertaAI/modeldb#638]
It looks like the function `log_model(model)` always tries to search the paths and build a huge zip file for uploading.

Is it possible to log model without any custom_modules? Thanks.

**Comment by convoliution** [comment]
Thanks for the question, @loveunk 

Much of the path-searching behavior can be skipped by passing an empty list as an argument: 
```python
run.log_model(my_model, custom_modules=[])
```
This will greatly reduce the size of the uploaded `custom_modules`.

Let me know if there's anything else I can help with, here!

**Comment by loveunk** [comment]
@convoliution Cool, thanks for your help.
