### ISSUE TITLE
Link to examples in README is broken

### ISSUE THREAD

**Issue by josepsmartinez** [VertaAI/modeldb#653]
The README at master branch point to a [link](https://docs.verta.ai/en/master/guides/examples.html) to detailed examples on how to use Verta client from Python. The link is broken.

**Comment by convoliution** [comment]
Thanks for the notice! I'll get that fixed up.

**Comment by convoliution** [comment]
While I'm fixing the links, you can find the examples we're referring to here:
https://docs.verta.ai/en/master/examples/examples.html

**Comment by convoliution** [comment]
Hey @jotapem,

This should be resolved as of #655, so I'll be closing this Issue.
Do let us know if you have further questions or comments, thanks!
